# Generated by Django 4.1.1 on 2022-09-18 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('job_start', models.CharField(blank=True, max_length=50, verbose_name='job_start')),
                ('med_check', models.CharField(blank=True, max_length=50, verbose_name='med_check')),
                ('accept_train', models.CharField(blank=True, max_length=50, verbose_name='accept_train')),
                ('accept_train_time_begin', models.DateTimeField()),
                ('accept_train_time_end', models.DateTimeField()),
                ('stations', models.CharField(blank=True, max_length=50, verbose_name='stations')),
                ('pass_train', models.CharField(blank=True, max_length=50, verbose_name='pass_train')),
                ('job_end', models.CharField(blank=True, max_length=50, verbose_name='job_end')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('level', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_city', models.CharField(blank=True, max_length=100)),
                ('city_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
