# Generated by Django 4.1.1 on 2022-09-18 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cities',
            old_name='city_id',
            new_name='Users',
        ),
    ]
