# Generated by Django 4.1.1 on 2022-09-18 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_city_id_cities_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mash',
            name='accept_train',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='mash',
            name='job_end',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='mash',
            name='job_start',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='mash',
            name='med_check',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='mash',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mash',
            name='pass_train',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='mash',
            name='stations',
            field=models.CharField(max_length=50, verbose_name='stations'),
        ),
    ]
