# Generated by Django 4.1.1 on 2022-09-18 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_mash_accept_train_alter_mash_job_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accept_train_time_begin', models.DateTimeField()),
                ('accept_train_time_end', models.DateTimeField()),
                ('stations', models.CharField(max_length=50, verbose_name='stations')),
            ],
        ),
        migrations.RemoveField(
            model_name='mash',
            name='accept_train_time_begin',
        ),
        migrations.RemoveField(
            model_name='mash',
            name='accept_train_time_end',
        ),
        migrations.RemoveField(
            model_name='mash',
            name='stations',
        ),
    ]
