# Generated by Django 4.1.1 on 2022-09-18 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_stations_stations'),
    ]

    operations = [
        migrations.AddField(
            model_name='mash',
            name='station',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.stations'),
        ),
        migrations.AlterField(
            model_name='stations',
            name='stations',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.cities'),
        ),
    ]
