# Generated by Django 4.1.1 on 2022-09-18 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_mash_station_alter_stations_stations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mash',
            name='station',
        ),
        migrations.AddField(
            model_name='mash',
            name='station1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.stations'),
        ),
    ]
