# Generated by Django 4.1.1 on 2022-09-18 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_mash_station_mash_station1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mash',
            name='station1',
        ),
    ]
