# Generated by Django 4.2.dev20220912110250 on 2022-09-18 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_assignment_delete_accept'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assignment',
        ),
    ]
